# Copyright 2019 The OpenTracing Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: java
jdk:
#- oraclejdk7
- oraclejdk8
- oraclejdk9
#- oraclejdk10
- oraclejdk11
install:
- cp settings.xml $HOME/.m2/settings.xml && rm -rf ~/.m2/repository/io/opentracing/contrib/java-specialagent
script:
- 'if [ "$TRAVIS_JDK_VERSION" = "oraclejdk8" ] &&
      [ "$TRAVIS_BRANCH" = "master" ] &&
      [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    sh -c "$SIGNING_KEY" | $GPG_EXECUTABLE --fast-import &> /dev/null &&
    mvn install && mvn -Ddeploy deploy;
  else
    mvn install;
  fi'
after_success:
- mvn -Ddeploy install
cache:
  directories:
    - ~/.m2/repository
env:
  global:
  - secure: T8map3YvsPrN82R+2gOyolPkFjr3GC7+WndMydaHfwZK5KKv3odCulUVve4nIpgGUpINDpmrzFEz21GM3ywLfopJFJKhPyQFpqkytycWrDZdYV0gqHYZpoHIM9vuVDjg9gZFISMMLCz7ygHWsTCdams89Gin62R+QZipOrh0JYDUA4cXz1e1d4GEnDj1/c3rRoB5WVgvxUfkBv2Bq2Rv4w8alKTsAtcqawmz9qGBmjFSKSq6w5OYsBAX4OaeUqZG2+kYkCB8lwGRhoXUWW6HBOWzDe/KFROV79dXWgL/3JC0l+GcJbEMUbO6QUZ63ceuum8qQ20Dg0IAlcMVJUnLz375qFcC1uejdD3d86BWMPVn4SDC5ZmbQpANOMtVg8RnMZn5sY3EVs/wADMTV/X0crAIuZoFAAQ3t175JtbSiOJkmPxLidOqr8SJNOwxQaKXgdnEzhBX1IesylTjbm8MOvyIW0cgVmeA23RafzDgLePMzWIoDKIQXEQ8haZZjbfHrNDEbVGhzFSdsxz98oc8jrkC7V8o0aoCGZzRZvqMvryvxppsVMmi1l5s225JnHbEZN7LOJML3beNPY87EMq8b8xosjnOnYB9qcp1lutmKCq3uANNU94S6LHFPcswwsBwuGQxHoThess/bGk6cwvO55UkjB0SKru6eXPleT3fWzU=
  - secure: Rv0tRiPqahdrngVwI6yIgGJVTMaPhme/CJkYZtiD/A/faBAHnegzsDgyetV9h41sOUwySsgEZxe39tCg5ZB8JkNyqouqcza5E9PT21txhPWn+Kw1g9CRvcyRP/O1mPJTjtbfhfE193MQFXVz8E46iWq5Ol7RIHgbKtdQgQ8yRTw/0SsBtu7z2WNq59DeFdWI/nZyfxEc2U+rcPihPgNZKD8cDzwFq2XvrXNiOuuqkQmicKdH+Ng+RCthoelGiDa2KEd8z0pruN4Y52n3kNd0wyU1E4dol1CASjRcj6cralZUu8FWMvmiM4JCCWvDAPqEC44X4sMbRm7Hda4j/R2C2KAfEJlivAId7wMz6ZH3K6vDbZzZl9h2smMcCQpTaZYU5qxhEGcF+jtZmPsCKEvmZZVMrJginpECWITrBnwZu/uA9FF8ywhfx+IKLfHcQGa/Wj/fYm+jq9oIxIYFDEhA+AXnL07FVTDfqlHsjMKg6RKantPhK1jXKurwRE9DObSs+m8N2ZZCtAFqy+baZ/fKyXfIKpFupCWaHqdxLVRZ9hI+LSv7awQA87xQlU7cNEiwQM1o8TaHSSM2WubN5QvxvOvqtKs5/Pam5sacrOwfDQkXc0jE7Ry6+pxyCobWtDR5ZSNZeXLJGCagDNuOaNPucUxPxbES7DvDPJuJNDEy8VQ=
  - secure: lGEwpFYzf28yZN0azEhnwtHD1tqGKgHZOWxsLcijbe6TCwoZz2s7WCWns3CDeSFBiNFxVwYwWvZqW0ni50h6OPTT9wTWsx0mzR68Z91FmD609eHa3cRCnkPK3uOByJ9iWlxitLbz5yhWJgxnqOsBjlKdgybRGcC8UObmbbcE1RQEbkRkQxfbr+BHwhqBRK8BN7Cg/3p7KeHxr1T91oN71HRiYCl/9TZgT/7ZdOgQsb4156uVdT7jSbH1rwW9P7UCLZklAUXGKXnkpslWYupIooAKNul7KCKJoYrrpPK/9Pmz0LOXhLDN/xWUUL3c7Wd13plu2AiIjgiNCnSJQezjja539psb+qkmZpYgwajWy9vY2PyvfnS9q1xZM/Ae0szmKRca0Xbkat4GLz4kjF22zZrNH8SKv7VJY0en4uQFwx2PwGiQlZTOkyI5KgQ1mT4pJQccL2el/TxRugIdBAkRYJ1w6bhF1L4CbnxZRizFuA2Q75FFWjkgZ0G32mNLKP8agoRrVAkS98Zpv4VA8Zp4jo541Sa2Zkfqt0eWQ/AoWJbGIUV5lsFaiVn8vbqyWLt/8in9W8tfktIflke6gCeUt6Fp1QQ7zBrxwNoEf5oer0ECcaz/16+iQXaId2qagwDNIKXGwwZNUVCJ+bMePM9brJan22ZP9b/vpLymZwyywTA=
  - secure: gSnZrWgGCNoMBKYNFXoD2dvw05yIQaaJuckmZzppO5ollFJdpg9B1GEIolfsFQ/AgU3+XpFsX4gqpkJq9RGanfWTTKnoI3Xnvl5M4CxLUkN1iHJFxFqeogBBkHYVOCDs8p/D8bjYjVrQJdBO+s3VJFPEUq3iEpP1IdzldNQGRc9I1J1NIIR4XNJYX1hTbl240amx9tNyeP8/2rAdm0eTYgx6aYi66rS162/UE7aVDNY8bVvAVNrjx4yN1qfEuv9a5MfBcvCGyNYV4wsHrfCcaaAi8wkFy2DjGThCxqm+TAV8NWb0mB8NLfeOOOxGPmRGwlF7QqPrf3Uculeq5woqI6ETtbmchXcSKgEVCNHjhfBQivhcWo2G3xjEIQdVfGoKQd2jkBvycxesgOpx+GamygbiGg72GAuxMn2LIojWOhlBEz3njG24rbNCFz62JP0X+gS1vs8zb0FepcjunhAiyzjm4lJaOdin/IzC71VVhfr/QWWzjedASh1UoG6y+Vxjhx8yQw2BKlbrsxhbrp2PKadK2c2ag4xV8kK7co1NPjBOXevdLUvtwyEfrD9BrkeD6ls/sIjdzKmJSAplp0jIbPOj1XkeHKHz52xEw10UVl39zhdHPVdeOnn1ytB+1yBAbYz5Hin0fvlY2RljuBLhvBKZCihFXLPpFmXDSVaH7K4=
  - secure: TH08PCNXT3zfgjqebxJWsSl/8yCgvNn2loEh4X/87pPmlsCVcRMkMEj3oWWkL26Ia4wIKcEvMyuYcsHMnirIIA+9iNE18pzULT4egrUubXH835g3PEK4lA2ES6iyn4/oVS5HI+EUbz1TNPLiH+T3zRjZDB6nVf9Qu7iA1yRSneCTQtgPXC0/9SQNUXW21j2NkrBspzJgAVzez4Lnkzgd4eVhXIKJhoOYJ9WP13a8dxz0s379+qOWxyJPvKbQ316AnEEfNG2qrqUfVFzcBJr1jrYpoLz5aTyWGq7vuw68K26ThArtlcwwQbdZVXlXXTEqgoytwI2xA2Pe3k6PAC6SmY3+LZrYVApGXo7vj6gsk35tVS9SQ3hspPZ62+3IZuJyyUiPYx5XW6929vDRzkUfeF3T7TOVou/RuCniW4Ucs7CRRa++GhumBDM+qvDKBLs6O/18ULhHgGBClOdLrlPp/yovX2NlWhw0c+EKMIyDIumg2Q/pa7K31MPGWgijnis28YbSUisV/NY/Y8B3H9vNlHk/08YCRWOdbawkWXsqq0FchrB7tuOfs8L2TsxTleTY3rS7tdUY3vO2L+wX7uHSJUEK+CU/aco9lRvvtKoHD9zQGDU5mVaLnc2A966Rt5nci8jXpKNvY9fHO2lg7azD61EEXBBFI8EWYdoxp7EKdN0=
  - secure: mR/c4iEN91B3YqfnmaPPGd+RxNiE8198wvjnkxhn43jmp9fD2Wzy3uy8tn+b1OZfKEqeizW6oeuzaVRY6fk0Ur9q5mlPI4Scb2S9V8mbIjNLLjB91XTSMn7T4mhQdxzsWCA41JbEYqBHyCXmLwleANjZgGoo/erSOBHDOx7vFhNOBHLp7LvzC92F9qjO4peEC7YRMxm8TQ7i/Yl+wrnRUveusV5wKF3xISkR41DhY2+c+sQ6AUPw0wVpu0YJuuPOLlFM2db34FK3cks30FYoiZkBHHJ8GYZLUNb3KicW0NKuISoTpgjd6ndtpFyDOTZuMePP0XPfwTopuGeZT5LIIsE78SMMxIPriQpREj1R1jRZdDW7/P2aMi8xngMPGHQMFOYW5pOZmmeNtfRbyc7u0gxt1NQ/+M2lebeVpFlWuHXgB/x/yaLJEaBm6L/mHQ3TYqUcUriJF0EwkAHvcvbIjez+16aX4NjkWvAjb8IGNJnQVR6CD8vzVjsqy1LGLCZDbDbMqSPFWPb/X/fXawaEXOWaEivvBDSktRacTq/XjcUpNNDcXZhiGvLeetHzSyUwjCB1WutvbNp7GNSsmzNjHQZUsOTqrm3G00RSkuaHKRA2mOqt89Mk9R3f59WDoNlHEK4X+wdTNdA8j/p4sjelzX51ZvXHKSvIFKv5AJTuK58=
