# Copyright 2019 The OpenTracing Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dist: trusty
language: java
cache:
  directories:
  - ~/.m2
before_install:
- 'export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn &&
   cp settings.xml $HOME/.m2/settings.xml;'
stages:
- install
- okhttp
- jdbc
- deploy
jobs:
  include:
  - stage: install
    jdk: oraclejdk8
    install: rm -rf ~/.m2/build ~/.m2/repository/io/opentracing/contrib/specialagent
    script:
    - 'if [ "$TRAVIS_BRANCH" = "master" ] &&
          [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        mvn -B -P report install &&
        mvn -B -DrepoToken=$REPO_TOKEN coveralls:report &&
        mvn -B -Dassemble install;
      else
        mvn -B install &&
        mvn -B -Dassemble install;
      fi'
    before_cache: find . -name target -exec rsync -R -r '{}' ~/.m2/build \;
  - stage: install
    jdk: oraclejdk11
    install: rm -rf ~/.m2/build ~/.m2/repository/io/opentracing/contrib/specialagent
    script:
    - 'mvn -B install &&
       mvn -B -Dassemble install;'
    before_cache: find . -name target -exec rsync -R -r '{}' ~/.m2/build \;
  - stage: deploy
    jdk: oraclejdk8
    install: rsync -r ~/.m2/build/ .
    script:
    - 'if [ "$TRAVIS_BRANCH" = "master" ] &&
          [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        sh -c "$SIGNING_KEY" | $GPG_EXECUTABLE --fast-import &> /dev/null &&
        mvn -B -Dassemble -P deploy deploy;
      fi'
  - stage: test
    jdk: oraclejdk8
    script: mvn -B -Dtest -P okhttp install
  - stage: test
    jdk: oraclejdk11
    script: mvn -B -Dtest -P okhttp install
  - stage: test
    jdk: oraclejdk8
    script: mvn -B -Dtest -P jdbc install
  - stage: test
    jdk: oraclejdk11
    script: mvn -B -Dtest -P jdbc install